# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-26 04:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courtNum', models.IntegerField(default=0)),
                ('courtReserved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Teamers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p1', models.CharField(max_length=250)),
                ('p2', models.CharField(max_length=250)),
                ('p3', models.CharField(max_length=250)),
                ('p4', models.CharField(max_length=250)),
                ('p5', models.CharField(max_length=250)),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reserveScreen.Court')),
            ],
        ),
    ]
