# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-18 01:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reserveScreen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p1', models.CharField(max_length=250)),
                ('p2', models.CharField(max_length=250)),
                ('p3', models.CharField(max_length=250)),
                ('p4', models.CharField(max_length=250)),
                ('p5', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='court',
            name='courtNum',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='court',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reserveScreen.Court'),
        ),
    ]
