# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-13 23:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserveScreen', '0002_auto_20180426_0429'),
    ]

    operations = [
        migrations.AddField(
            model_name='court',
            name='halfreserved',
            field=models.BooleanField(default=False),
        ),
    ]
