# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-20 05:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loaded_Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=200)),
                ('defense', models.CharField(max_length=250)),
                ('offense', models.CharField(max_length=100)),
                ('team_pic', models.CharField(max_length=1000)),
                ('members', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(max_length=10)),
                ('player_name', models.CharField(max_length=200)),
                ('loaded_team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courts1.Loaded_Team')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=200)),
                ('defense', models.CharField(max_length=250)),
                ('offense', models.CharField(max_length=100)),
                ('team_pic', models.CharField(max_length=1000)),
                ('members', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courts1.Team'),
        ),
    ]
