# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-13 21:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts1', '0002_auto_20180426_0427'),
    ]

    operations = [
        migrations.AddField(
            model_name='loaded_team',
            name='isplaying',
            field=models.BooleanField(default=False),
        ),
    ]
