# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-14 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts1', '0003_loaded_team_isplaying'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='player_lt_valhe',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
