# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-14 14:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courts1', '0004_player_player_lt_valhe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='player_lt_valhe',
            new_name='player_lt_value',
        ),
    ]
